
name: Semantic Release


on:
  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:

  build:
    
    runs-on: ubuntu-latest

    
    steps: 
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

     

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}     
        run: npx semantic-release